# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'http_request_response' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for http_request_response
  pod 'Alamofire', '~> 4'
  pod 'ObjectMapper', '~> 3'

end
