# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'endpoint_ping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for endpoint_ping
  pod "PlainPing"

  target 'endpoint_pingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'endpoint_pingUITests' do
    # Pods for testing
  end

end
